---
title: "githubdplyr"
author: "jalil"
format: html
editor: visual
---

```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
```

```{r}
library(readr)
here::i_am("dyplrrevisions.Rproj")
library(here)
spotify <- read_rds("top-spotify-hits-2000-2019.Rds")
```

```{r}
ggplot(spotify, aes(x=tempo, color=key))+
         geom_density()
```

```{r}
spotify |>
  distinct(genre) |>
  nrow()
## helps count the number of distinct values
```

```{r}
spotify |>
  group_by(year) |>
  summarise(n = mean(popularity))
## if you wanna summarise smthg
```

```{r}
spotify |>
distinct(song, .keep_all = TRUE) |>
  group_by(artist) |>
  summarise(n = n()) |>
  arrange(-n) |>
  slice(1:5)
```

```{r}
spotify |>
  distinct(song, .keep_all = TRUE) |>
  group_by(genre) |>
  summarise(minimum=min(tempo), median=median(tempo), maximum=max(tempo), n=n()) |>
  arrange(-n) |>
  filter(n > 10)
```

```{r}
spotify |>
  separate_wider_delim(genre, delim = ",", names=c("genre1", "genre2", "genre3", too_few = "align_start"/"align_end", too_many= "merge"))
```

```{r}
library(readr)
here::i_am("dyplrrevisions.Rproj")
library(here)
library(vroom)
white_wine <- vroom("winequality-white.csv")
```

```{r}
nrow(white_wine)
ncol(white_wine)
```

```{r}
class(white_wine)
class(white_wine$quality)
white_wine$quality |> class()
white_wine[["quality"]] |> class()
white_wine |>
  pull(quality) |>
  class()
```

```{r}
#| eval: false
#| code-fold: false
ggplot(white_wine, aes(x=quality, fill=quality))+
  geom_bar()
```

```{r}
white_wine$quality <- factor(white_wine$quality,
                             ordered = TRUE,
                             levels = 3:9)
```


```{r}
white_wine <- white_wine |>
  mutate(quality = factor(quality, ordered=TRUE, levels=3:9))
```

```{r}
ggplot(white_wine, aes(x = quality, fill = quality)) +
  geom_bar()
```

## Create new variables
```{r}
white_wine <- white_wine |>
  mutate(`capturate sulfur dioxyde` = `total sulfur dioxide` - `free sulfur dioxide`,
         `free sd %` = `free sulfur dioxide` / `total sulfur dioxide` * 100)
```

```{r}
ggplot(white_wine, aes(x=`free sd %`, y=`total sulfur dioxide`, color=`free sulfur dioxide`))+
  geom_point(alpha=0.2)
```

```{r}
white_wine |>
  group_by(quality) |>
  summarise("median free sulfites"=median(`free sd %`))
```

```{r}
white_wine |>
  select(`fixed acidity`, `volatile acidity`, `citric acid`, pH) |>
  arrange(-`fixed acidity`)
```

```{r}
ggplot(white_wine, aes(x=pH, y=`volatile acidity`))+
  geom_point(alpha=0.2)
```

```{r}
white_wine |>
  select(1:3)
```

```{r}
#| eval: false
white_wine |>
  select(where( \(x) is.numeric(x) & (max(x) < 5)))
```

```{r}
white_wine|>
  filter(alcohol > 14) |>
  select(alcohol, quality)
```

```{r}
ggplot(white_wine, aes(x=alcohol))+
  geom_density()+
  geom_rug(alpha=0.1)
```

```{r}
white_wine |>
  filter(alcohol >= 13, `citric acid` < 1) |>
  ggplot(aes(x = `citric acid`, y = `residual sugar`, color = alcohol)) +
  geom_point(alpha = 0.75) +
  facet_wrap(vars(quality), scales = "free")
   scale_color_viridis_c()
```

```{r}
white_wine <- white_wine |>
  mutate(`alcohol category` = case_when(alcohol <= 9 ~ "low",
                                        alcohol >= 13 ~ "high",
                                        .default = "medium"))
```

```{r}
ggplot(white_wine, aes(y=quality, fill=`alcohol category`))+
  geom_bar(position = "fill")
```

```{r}
white_wine |>
  summarise(med_alcohol=median(alcohol),
           sd(alcohol))
```

```{r}
white_wine <- white_wine |>
  mutate(spread_alcohol=alcohol - median(alcohol))
```

```{r}
ggplot(white_wine, aes(x=spread_alcohol, fill=quality)) +
       geom_density()
```

```{r}
white_wine <- white_wine |>
  mutate(na = (alcohol - mean(alcohol))/ sd(alcohol))
ggplot(white_wine, aes(x=na, fill=quality))+
  geom_density()
```

```{r}
white_wine |>
  group_by(quality) |>
  summarise(mean(alcohol),
            median(alcohol),
            sd(alcohol),
            IQR(alcohol),
            n())
```

```{r}
quantile(white_wine$`residual sugar`)
quantile(white_wine$alcohol)
```

```{r}
quantile(white_wine$`residual sugar`, probs=seq(0,1,0.05))
```

```{r}
white_wine |>
  reframe(quantile(`residual sugar`),
          mean(`residual sugar`))
```

```{r}
sugar_stats <- white_wine |>
  summarise(list(quantile(`residual sugar`)),
            mean(`residual sugar`))
```


```{r}
white_wine |>
  summarise(median(`residual sugar`),
            n(),
            .by = quality) |>
  arrange(quality)
```

```{r}
white_wine |>
  group_by(quality) |>
  summarise(median = median(`residual sugar`),
            n = n())
```

```{r}
white_wine |> 
  mutate(ha = alcohol >= 12.5 ) |> 
  summarise(median(`residual sugar`),
            n(),
            .by = ha) 
```

```{r}
white_wine |> 
  mutate(alcohol_class = cut(alcohol, breaks = c(7, 8, 9, 10, 11, 12, 13, 15), 
                             ordered_result = TRUE)) |> 
  summarise(median(`residual sugar`),
            median(pH),
            mean(quality),
            n(),
            .by = alcohol_class) 
```



```{r}
white_wine |> 
  mutate(alcohol_class = cut(alcohol, breaks = c(7, 9, 10, 12, 13, 15), 
                             ordered_result = TRUE)) |> 
  ggplot(aes(y=alcohol_class, fill=quality)) +
  geom_bar(position= "fill")
```

```{r}
ggplot(white_wine, aes(x=alcohol, y=quality)) +
  geom_boxplot()
```
```{r}
alcohol_quantiles <- 
  white_wine |> 
  pull(alcohol) |>
  quantile(probs = seq(0, 1, by = 0.1))
alcohol_quantiles
```



